accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('home/', views.home_view, name='home'), 
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('pedidos/', views.pedidos_view, name='pedidos'),
    path('add-produto/', views.add_produto_view, name='add_produto'),
    path('favoritos/', views.favoritos_view, name='favoritos_view'),
    path('add-categoria/', views.add_categoria_view, name='add_categoria'),

    path('incluir-pedido/<int:produto_id>/', views.incluir_pedido, name='incluir_pedido'),
    path('pedidos/delete/<int:id>/', views.delete_pedido, name='delete_pedido'),
    path('update_produto/<int:id>/', views.update_produto, name='update_produto'),
    path('produto/<int:produto_id>/delete/', views.delete_produto, name='delete_produto'),
    path('toggle-favorito/<int:produto_id>/', views.toggle_favorito, name='toggle_favorito'),
    path('enviar_whatsapp/', views.enviar_whatsapp, name='enviar_whatsapp'),
]


restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

# Importações para o Swagger
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

# Configuração do Swagger
schema_view = get_schema_view(
   openapi.Info(
      title="Restaurant API",
      default_version='v1',
      description="API para gerenciamento de restaurante",
      terms_of_service="https://www.example.com/terms/",
      contact=openapi.Contact(email="contact@example.com"),
      license=openapi.License(name="MIT License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),  # Inclui as rotas do app accounts
    
    # Rotas da API REST
    path('api/', include('accounts.api_urls')),
    
    # Swagger
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),  # Adicione aqui o logout
    path('', RedirectView.as_view(url='/accounts/login/', permanent=False)),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator, MinLengthValidator
from django.core.exceptions import ValidationError
import re

def validate_nome_categoria(value):
    if re.search(r'[^a-zA-Z0-9\s\-àáâãéêíóôõúçÀÁÂÃÉÊÍÓÔÕÚÇ]', value):
        raise ValidationError('O nome da categoria não pode conter caracteres especiais')
    
    if len(value) < 3:
        raise ValidationError('O nome da categoria deve ter pelo menos 3 caracteres')

class Categoria(models.Model):
    nome = models.CharField(
        max_length=255, 
        validators=[validate_nome_categoria],
        unique=True
    )
    descricao = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.nome

    def clean(self):
        # Convertendo o nome para title case (primeira letra de cada palavra em maiúsculo)
        self.nome = self.nome.title()
        super().clean()

def validate_produto_nome(value):
    if len(value) < 3:
        raise ValidationError('O nome do produto deve ter pelo menos 3 caracteres')

class Produto(models.Model):
    nome = models.CharField(max_length=255, validators=[validate_produto_nome])
    preco = models.DecimalField(
        max_digits=10, 
        decimal_places=2,
        validators=[
            MinValueValidator(0.01, message='O preço deve ser maior que zero'),
            MaxValueValidator(10000, message='O preço não pode ser maior que R$10.000')
        ]
    )
    imagem = models.ImageField(upload_to='produtos/', default='produtos/default.jpg')
    descricao = models.TextField(validators=[MinLengthValidator(10, 'A descrição deve ter pelo menos 10 caracteres')])
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, null=True, blank=True, related_name='produtos')

    def is_favorito(self, usuario):
        return self.favorito_set.filter(usuario=usuario).exists()

    def clean(self):
        if not self.categoria:
            raise ValidationError('Um produto deve pertencer a uma categoria')
        super().clean()

class Pedido(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField(
        validators=[
            MinValueValidator(1, message='A quantidade mínima é 1'),
            MaxValueValidator(100, message='A quantidade máxima é 100')
        ]
    )
    preco_total = models.DecimalField(max_digits=10, decimal_places=2, editable=False)
    data_criacao = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.preco_total = self.produto.preco * self.quantidade
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Pedido de {self.usuario.username} - {self.produto.nome} (Quantidade: {self.quantidade})"
    
class Favorito(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('usuario', 'produto')

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Produto, Categoria
from django.db import models


# Formulário de registro
class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class ProdutoForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = ['nome', 'descricao', 'preco', 'imagem', 'categoria']  # Adicione 'categoria' aqui

    categoria = forms.ModelChoiceField(queryset=Categoria.objects.all(), required=True)


class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['nome']

accounts/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth import authenticate, login
from .models import Produto, Pedido, Favorito, Categoria
from .forms import RegisterForm, ProdutoForm, CategoriaForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db.models import Q
from django.http import JsonResponse
from urllib.parse import urlencode
from django.utils.timezone import now

# View de registro
def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Conta criada com sucesso!')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request, 'accounts/register.html', {'form': form})

# View de login
def login_view(request):

    if request.user.is_authenticated:
        return redirect('home')
    
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home') 
        else:
            messages.error(request, 'Usuário ou senha inválidos')
    return render(request, 'accounts/login.html')

# View de Home (apenas usuários logados podem acessar)
@login_required(login_url='login')
def home_view(request):
    produtos = Produto.objects.all()
    categorias = Categoria.objects.all()

    search = request.GET.get('search', '')
    if search:
        produtos = produtos.filter(nome__icontains=search) | produtos.filter(descricao__icontains=search)

    categoria_id = request.GET.get('categoria')
    if categoria_id:
        produtos = produtos.filter(categoria__id=categoria_id)

    favoritos = Favorito.objects.filter(usuario=request.user).values_list('produto_id', flat=True)

    for produto in produtos:
        produto.is_favorito = produto.id in favoritos

    produtos_por_categoria = {}
    for categoria in categorias:
        produtos_por_categoria[categoria] = produtos.filter(categoria=categoria)

    return render(request, 'accounts/home.html', {
        'produtos_por_categoria': produtos_por_categoria,
        'categorias': categorias,
        'selected_categoria': categoria_id
    })



# Verifica se o usuário é admin
def is_admin(user):
    return user.is_superuser

# View para adicionar produto (restrito a admins)
@login_required
@user_passes_test(is_admin)
def add_produto_view(request):
    if request.method == 'POST':
        form = ProdutoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Produto adicionado com sucesso!')
            return redirect('home')
    else:
        form = ProdutoForm()

    categorias = Categoria.objects.all()

    return render(request, 'accounts/add_produto.html', {'form': form, 'categorias': categorias})    

# View para editar produto (restrito a admins)
@login_required
@user_passes_test(is_admin)
def update_produto(request, id):
    produto = get_object_or_404(Produto, id=id)

    if request.method == 'POST':
        preco = request.POST.get('preco', '').replace(',', '.')
        data = request.POST.copy()
        data['preco'] = preco

        form = ProdutoForm(data, request.FILES, instance=produto)
        if form.is_valid():
            form.save()
            return redirect('home') 
    else:
        form = ProdutoForm(instance=produto)

    categorias = Categoria.objects.all()

    return render(request, 'accounts/update_produto.html', {'form': form, 'produto': produto, 'categorias': categorias})

@login_required
@user_passes_test(is_admin)
def delete_produto(request, produto_id):
    produto = get_object_or_404(Produto, id=produto_id)
    if request.method == 'POST':
        produto.delete()
        messages.success(request, 'Produto deletado com sucesso!')
        return redirect('home')
    return redirect('update_produto', id=produto_id)

@login_required
def incluir_pedido(request, produto_id):
    produto = get_object_or_404(Produto, id=produto_id)

    if request.method == 'POST':
        quantidade = int(request.POST.get('quantidade', 1)) 
        pedido = Pedido(usuario=request.user, produto=produto, quantidade=quantidade)
        pedido.save()

        return JsonResponse({'success': True, 'message': 'Produto incluído no pedido com sucesso!'})

    return JsonResponse({'success': False, 'message': 'Erro ao incluir o produto.'})

@login_required
def pedidos_view(request):
    pedidos = Pedido.objects.filter(usuario=request.user)
    total = sum(pedido.preco_total for pedido in pedidos)
    return render(request, 'accounts/pedidos.html', {'pedidos': pedidos, 'total': total})

@login_required
def delete_pedido(request, id):
    pedido = get_object_or_404(Pedido, id=id, usuario=request.user)
    if request.method == 'POST':
        pedido.delete()
        messages.success(request, 'Pedido excluído com sucesso!')
        return redirect('pedidos')
    return redirect('pedidos')

@login_required
def toggle_favorito(request, produto_id):
    produto = get_object_or_404(Produto, id=produto_id)
    favorito, created = Favorito.objects.get_or_create(usuario=request.user, produto=produto)

    if not created:
        favorito.delete()  
    message = "Produto adicionado aos favoritos!" if created else "Produto removido dos favoritos!"
    return JsonResponse({'success': True, 'message': message})

@login_required
def favoritos_view(request):
    favoritos = Favorito.objects.filter(usuario=request.user).select_related('produto')
    return render(request, 'accounts/favoritos.html', {'favoritos': favoritos})

@login_required
@user_passes_test(is_admin)
def add_categoria_view(request):
    if request.method == 'POST':
        form = CategoriaForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Categoria criada com sucesso!')
            return redirect('home')
    else:
        form = CategoriaForm()
    return render(request, 'accounts/add_categoria.html', {'form': form})

@login_required
def enviar_whatsapp(request):
    pedidos = Pedido.objects.filter(usuario=request.user)

    if not pedidos.exists():
        messages.error(request, "Você não tem pedidos para enviar.")
        return redirect('pedidos')

    detalhes_pedidos = "\n".join(
        [
            f"{pedido.quantidade}x {pedido.produto.nome} - R$ {pedido.preco_total:.2f}"
            for pedido in pedidos
        ]
    )
    total = sum(pedido.preco_total for pedido in pedidos)

    nome_cliente = request.user.first_name or request.user.username
    data_pedido = now().strftime("%d/%m/%Y %H:%M")

    mensagem = (
        f"*Novo Pedido Realizado!*\n\n"
        f"*Data do Pedido:* {data_pedido}\n"
        f"*Cliente:* {nome_cliente}\n\n"
        f"*Detalhes do Pedido:*\n{detalhes_pedidos}\n\n"
        f"*Total:* R$ {total:.2f}\n\n"
        f"*Ação Necessária:* Por favor, envie:\n"
        f"O endereço completo para entrega.\n"
        f"O método de pagamento escolhido (dinheiro, cartão, etc.).\n\n"
        f"Após enviar essas informações, confirme para que possamos processar o pedido."
    )

    numero_destino = "5518981969555" 

    mensagem_codificada = urlencode({"text": mensagem})

    whatsapp_url = f"https://wa.me/{numero_destino}?{mensagem_codificada}"

    return redirect(whatsapp_url)

accounts/templates/accounts/add_categoria.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Adicionar Produto</title>
    {% tailwind_css %}
  </head>
  <body class="bg-dark-400">
    {% include 'accounts/header.html' %}

    <div class="flex flex-col justify-center mx-auto">
      <form method="POST" enctype="multipart/form-data" class="flex flex-col justify-center items-start max-w-[1320px] gap-7 mt-[180px] mx-auto">
        {% csrf_token %}
        <a href="{% url 'home' %}" class="flex items-center">
          <img class="w-8 h-8" src="{% static 'accounts/images/back.svg' %}" alt="back" />
          <p class="font-bold font-poppins text-light-300 text-2xl">voltar</p>
        </a>

        <h1 class="font-poppins text-[32px] text-light-300">Adicionar categoria</h1>

        <div >
          <div class="flex gap-8">
            <div class="flex flex-col gap-4">
              <label class="text-light-400" for="id_nome">Nome da Categoria:</label>
              <div class="flex gap-2 bg-dark-800 py-3 px-8 rounded-lg w-80">
                <input class=" focus:ring-0 font-poppins bg-dark-800 focus:border-none border-none w-full" type="text" name="nome" id="id_nome" placeholder="Ex.: Entrada" value="{{ form.nome.value|default_if_none:'' }}" />
              </div>
              {% if form.nome.errors %}
                <div class="text-red-500 mt-2">
                  {% for error in form.nome.errors %}
                    <p>{{ error }}</p>
                  {% endfor %}
                </div>
              {% endif %}
            </div>

          </div>

          <div class="flex flex-col gap-4 mt-10">
            <label class="text-light-400" for="id_descricao">Descrição</label>
            <div class="flex gap-2 bg-dark-800 py-3 px-8 rounded-lg">
              <input class=" focus:ring-0 w-full pb-28 font-poppins bg-dark-800 focus:border-none border-none" name="descricao" type="text" id="id_descricao" class="form-control" placeholder="Fale brevemente sobre a categoria" value="{{ form.descricao.value|default_if_none:'' }}" />
            </div>
            {% if form.descricao.errors %}
              <div class="text-red-500 mt-2">
                {% for error in form.descricao.errors %}
                  <p>{{ error }}</p>
                {% endfor %}
              </div>
            {% endif %}
          </div>
          <div class="flex justify-end">
            <button type="submit" class="mt-10 px-6 py-3 bg-tomato-100 rounded-md hover:bg-tomato-200 transition duration-200 ease-in-out">Salvar alterações</button>
          </div>
        </div>
      </form>
    </div>

    {% include 'accounts/footer.html' %}
  </body>
</html>

accounts/templates/accounts/add_produto.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Adicionar Produto</title>
    {% tailwind_css %}
  </head>
  <body class="bg-dark-400">
    {% include 'accounts/header.html' %}

    <div class="flex flex-col justify-center mx-auto">
      <form method="POST" enctype="multipart/form-data" class="flex flex-col justify-center items-start max-w-[1320px] gap-7 mt-[180px] mx-auto">
        {% csrf_token %}
        <a href="{% url 'home' %}" class="flex items-center">
          <img class="w-8 h-8" src="{% static 'accounts/images/back.svg' %}" alt="back" />
          <p class="font-bold font-poppins text-light-300 text-2xl">voltar</p>
        </a>

        <h1 class="font-poppins text-[32px] text-light-300">Adicionar prato</h1>

        <div>
          <div class="flex gap-8">
            <div class="flex flex-col gap-4">
              <label for="id_imagem" class="text-light-400">Imagem do prato</label>
              <input class="focus:ring-0 hidden" type="file" name="imagem" id="id_imagem" accept="image/*" />
              <div class="flex items-center gap-2 bg-dark-800 py-5 px-8 rounded-lg hover:bg-dark-1000 cursor-pointer" onclick="document.getElementById('id_imagem').click();">
                <img id="upload-icon" class="h-6 w-6" src="{% static 'accounts/images/download.svg' %}" alt="icon download" />
                <p id="upload-text" class="font-poppins">Selecione imagem</p>
                <p id="file-name" class="font-poppins text-light-100"></p>
              </div>
              {% if form.imagem.errors %}
                <div class="text-red-500 mt-2">
                  {% for error in form.imagem.errors %}
                    <p>{{ error }}</p>
                  {% endfor %}
                </div>
              {% endif %}
            </div>

            <div class="flex flex-col gap-4">
              <label class="text-light-400" for="id_nome">Nome</label>
              <div class="flex gap-2 bg-dark-800 py-3 px-8 rounded-lg">
                <input class="focus:ring-0 font-poppins bg-dark-800 focus:border-none border-none" type="text" name="nome" id="id_nome" placeholder="Ex.: Salada Ceasar" value="{{ form.nome.value|default_if_none:'' }}" />
              </div>
              {% if form.nome.errors %}
                <div class="text-red-500 mt-2">
                  {% for error in form.nome.errors %}
                    <p>{{ error }}</p>
                  {% endfor %}
                </div>
              {% endif %}
            </div>

            <div class="flex flex-col gap-4">
              <label class="text-light-400" for="id_preco">Preço</label>
              <div class="flex gap-2 bg-dark-800 py-3 px-8 rounded-lg">
                <input class="focus:ring-0 font-poppins bg-dark-800 focus:border-none border-none" type="number" name="preco" id="id_preco" placeholder="R$ 00,00" value="{{ form.preco.value|default_if_none:'' }}" />
              </div>
              {% if form.preco.errors %}
                <div class="text-red-500 mt-2">
                  {% for error in form.preco.errors %}
                    <p>{{ error }}</p>
                  {% endfor %}
                </div>
              {% endif %}
            </div>

            <div class="flex flex-col gap-4">
              <label class="text-light-400" for="id_categoria">Categoria</label>
              <div class="flex gap-2 bg-dark-800 py-3 px-8 rounded-lg">
                <select name="categoria" id="id_categoria" class="font-poppins bg-dark-800 focus:border-none focus:ring-0 border-none">
                  <option class="text-dark-200" value="">Selecione uma categoria</option>
                  {% for categoria in categorias %}
                    <option value="{{ categoria.id }}">{{ categoria.nome }}</option>
                  {% endfor %}
                </select>
              </div>
              {% if form.categoria.errors %}
                <div class="text-red-500 mt-2">
                  {% for error in form.categoria.errors %}
                    <p>{{ error }}</p>
                  {% endfor %}
                </div>
              {% endif %}
            </div>
          </div>

          <div class="flex flex-col gap-4 mt-10">
            <label class="text-light-400" for="id_descricao">Descrição</label>
            <div class="flex gap-2 bg-dark-800 py-3 px-8 rounded-lg">
              <input class="focus:ring-0 w-full pb-28 font-poppins bg-dark-800 focus:border-none border-none" name="descricao" type="text" id="id_descricao" class="form-control" placeholder="Fale brevemente sobre o prato, seus ingredientes e composição" value="{{ form.descricao.value|default_if_none:'' }}" />
            </div>
            {% if form.descricao.errors %}
              <div class="text-red-500 mt-2">
                {% for error in form.descricao.errors %}
                  <p>{{ error }}</p>
                {% endfor %}
              </div>
            {% endif %}
          </div>
          <div class="flex justify-end">
            <button type="submit" class="mt-10 px-6 py-3 bg-tomato-100 rounded-md hover:bg-tomato-200 transition duration-200 ease-in-out">Salvar alterações</button>
          </div>
        </div>
      </form>
    </div>

    {% include 'accounts/footer.html' %}
  </body>
</html>

<script>
  document.getElementById('id_imagem').addEventListener('change', function () {
    const fileName = this.files[0] ? this.files[0].name : 'Nenhum arquivo selecionado'
    const uploadIcon = document.getElementById('upload-icon')
    const uploadText = document.getElementById('upload-text')
    const fileNameDisplay = document.getElementById('file-name')
  
    if (this.files.length > 0) {
      uploadIcon.style.display = 'none'
      uploadText.style.display = 'none'
      fileNameDisplay.textContent = fileName
    } else {
      uploadIcon.style.display = 'block'
      uploadText.style.display = 'block'
      fileNameDisplay.textContent = ''
    }
  })
</script>

accounts/templates/accounts/footer.html
{% load static %}
<footer class="flex h-[77px] bg-dark-600 items-center px-32 mt-36">
    <div class='flex items-center gap-2.5 flex-1 px-'>
        <img class='w-8 h-8' src="{% static 'accounts/images/explorer-footer.svg' %}" alt="icon" />
        <p class='text-light-700 font-bold text-2xl'>Food explorer</p>
    </div>
    <p class='text-light-200'>© 2023 - Todos os direitos reservados.</p>
</footer>

accounts/templates/accounts/update_produto.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Adicionar Produto</title>
    {% tailwind_css %}
  </head>
  <body class="bg-dark-400">
    {% include 'accounts/header.html' %}

    <div class="flex flex-col justify-center mx-auto">
      <form method="POST" enctype="multipart/form-data" class="flex flex-col justify-center items-start max-w-[1320px] gap-7 mt-[180px] mx-auto">
        {% csrf_token %}
        <a href="{% url 'home' %}" class="flex items-center">
          <img class="w-8 h-8" src="{% static 'accounts/images/back.svg' %}" alt="back" />
          <p class="font-bold font-poppins text-light-300 text-2xl">voltar</p>
        </a>

        <h1 class="font-poppins text-[32px] text-light-300">Adicionar prato</h1>

        <div>
          <div class="flex gap-8">
            <div class="flex flex-col gap-4">
              <label for="id_imagem" class="text-light-400">Imagem do prato</label>
              <input class="hidden" type="file" name="imagem" id="id_imagem" accept="image/*" />
              <div class="flex items-center gap-2 bg-dark-800 py-5 px-8 rounded-lg hover:bg-dark-1000 cursor-pointer" onclick="document.getElementById('id_imagem').click();">
                <img id="upload-icon" class="h-6 w-6" src="{% static 'accounts/images/download.svg' %}" alt="icon download" />
                <p id="upload-text" class="font-poppins">Selecione imagem</p>
                <p id="file-name" class="font-poppins text-light-100"></p>
              </div>
              {% if form.imagem.errors %}
                <div class="text-red-500 mt-2">
                  {% for error in form.imagem.errors %}
                    <p>{{ error }}</p>
                  {% endfor %}
                </div>
              {% endif %}
            </div>

            <div class="flex flex-col gap-4">
              <label class="text-light-400" for="id_nome">Nome</label>
              <div class="flex gap-2 bg-dark-800 py-3 px-8 rounded-lg">
                <input class="font-poppins bg-dark-800 focus:border-none focus:ring-0 border-none" type="text" name="nome" id="id_nome" placeholder="Ex.: Salada Ceasar" value="{{ form.nome.value|default_if_none:'' }}" />
              </div>
              {% if form.nome.errors %}
                <div class="text-red-500 mt-2">
                  {% for error in form.nome.errors %}
                    <p>{{ error }}</p>
                  {% endfor %}
                </div>
              {% endif %}
            </div>

            <div class="flex flex-col gap-4">
              <label class="text-light-400" for="id_preco">Preço</label>
              <div class="flex items-center bg-dark-800 py-3 px-8 rounded-lg">
                <p class="">R$</p>
                <input class="font-poppins bg-dark-800 focus:border-none focus:ring-0 border-none" type="text" name="preco" id="id_preco" placeholder="R$ 00,00" value="{{ form.preco.value|default_if_none:'' }}" />
              </div>
              {% if form.preco.errors %}
                <div class="text-red-500 mt-2">
                  {% for error in form.preco.errors %}
                    <p>{{ error }}</p>
                  {% endfor %}
                </div>
              {% endif %}
            </div>

<div class="flex flex-col gap-4">
  <label class="text-light-400" for="id_categoria">Categoria</label>

  <div class="flex gap-2 bg-dark-800 py-3 px-8 rounded-lg">
    <select 
      name="categoria" 
      id="id_categoria" 
      class="font-poppins bg-dark-800 focus:outline-none focus:ring-0 border-none w-full"
    >
      {% for categoria in categorias %}
        <option 
          value="{{ categoria.id }}" 
          {% if form.instance.categoria.id == categoria.id %}selected{% endif %}
        >
          {{ categoria.nome }}
        </option>
      {% endfor %}
    </select>
  </div>
  

  {% if form.categoria.errors %}
    <div class="text-red-500 mt-2">
      {% for error in form.categoria.errors %}
        <p>{{ error }}</p>
      {% endfor %}
    </div>
  {% endif %}
</div>

          </div>

          <div class="flex flex-col gap-4 mt-10">
            <label class="text-light-400" for="id_descricao">Descrição</label>
            <div class="flex gap-2 bg-dark-800 py-3 px-8 rounded-lg">
              <input class="w-full pb-28 font-poppins bg-dark-800 focus:border-none focus:ring-0 border-none" name="descricao" type="text" id="id_descricao" class="form-control" placeholder="Fale brevemente sobre o prato, seus ingredientes e composição" value="{{ form.descricao.value|default_if_none:'' }}" />
            </div>
            {% if form.descricao.errors %}
              <div class="text-red-500 mt-2">
                {% for error in form.descricao.errors %}
                  <p>{{ error }}</p>
                {% endfor %}
              </div>
            {% endif %}
          </div>
          <div class="flex justify-end">
            <button type="submit" class="mt-10 px-6 py-3 bg-tomato-100 rounded-md hover:bg-tomato-200 transition duration-200 ease-in-out">Salvar alterações</button>
          </div>
        </div>
      </form>
      <form method="POST" action="{% url 'delete_produto' produto.id %}" class="-mt-12 flex justify-end max-w-[1000px]">
        {% csrf_token %}
        <button type="submit" class="px-6 py-3 bg-dark-800 rounded-md hover:bg-dark-1000 transition duration-200 ease-in-out" onclick="return confirm('Tem certeza que deseja deletar este produto?')">Excluir produto</button>
      </form>
    </div>

    {% include 'accounts/footer.html' %}
  </body>
</html>

<script>
  document.getElementById('id_imagem').addEventListener('change', function () {
    const fileName = this.files[0] ? this.files[0].name : 'Nenhum arquivo selecionado'
    const uploadIcon = document.getElementById('upload-icon')
    const uploadText = document.getElementById('upload-text')
    const fileNameDisplay = document.getElementById('file-name')
  
    if (this.files.length > 0) {
      uploadIcon.style.display = 'none'
      uploadText.style.display = 'none'
      fileNameDisplay.textContent = fileName
    } else {
      uploadIcon.style.display = 'block'
      uploadText.style.display = 'block'
      fileNameDisplay.textContent = ''
    }
  })
</script>